#%RAML 1.0
---
title: 测试
baseUri: http://api.e-bookmobile.com/{version}
version: v1


types:
  accountRequest: !include types/account-request.yaml
  successResponses: !include types/seccess-responses.yaml

/users:
  displayName: 用户中心
  get:
    queryParameters:
      author:
        displayName: Author
        type: string
        description: An author's full name
        example: Mary Roach
    description: Retrieve a specific book title
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "data": {
                  "id": "SbBGk",
                  "title": "Stiff: The Curious Lives of Human Cadavers",
                  "description": null,
                  "datetime": 1341533193,
                  "genre": "science",
                  "author": "Mary Roach",
                  "link": "http://e-bookmobile.com/books/Stiff",
                },
                "success": true,
                "status": 200
              }

/login:
  displayName: 登陆
  post:
    description: 用户登陆接口
    body:
      application/json:
        type: accountRequest
    responses:
      200:
        body:
          application/json:
            type: successResponses
            example: !include examples/success-responses.json

/register:
  displayName: 注册
  post:
    description: 新用户注册
    body:
      application/json:
        type: accountRequest
    responses:
      200:
        body:
          application/json:
            type: successResponses
            example: !include examples/success-responses.json


/todos:
  get:
  post:
  /{Id}:
    get:
    post:
    delete:

